from app import *

if __name__ == '__main__':
    char = Character(Halfling)
    char.level_up(Ninja)
    char.level_up(Wizard)
    char.level_up(Ninja)
    char.level_up(Wizard)
    char.level_up(Ninja)
    char.level_up(Wizard)
    char.level_up(Ninja)
    char.level_up(Wizard)
    char.level_up(Wizard)
    char.level_up(Ninja)
    char.level_up(Wizard)
    char.level_up(Ninja)
    char.level_up(Wizard)
    char.level_up(Ninja)
    print(char)
    print(char.hit_die(5).roll)
